name: patientmobileapplication
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:

  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  sign_button: ^2.0.6
  onscreen_num_keyboard: ^1.0.4
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  image_picker: ^1.0.7
  email_validator: ^2.1.17
  url_launcher: ^6.2.5
  maps_launcher: ^2.2.1
  share_plus: ^7.2.2
  http: ^1.2.0
  hive: ^2.2.3
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  mockito: ^5.4.4
  flutter_pdfview: ^1.3.2
  pdfx: ^2.6.0
  dio: ^5.4.3+1
  http_parser: ^4.0.2
  photo_view: ^0.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
